---
title: "Aula 3 - Análise de Medicamentos"
output: html_notebook
---

```{r}
library(tidyverse)
library(fs)
library(zip)
```

Listar diretório "Data"

```{r}
dir_ls("data")

```

Extrair Zip
```{r}
unzip("data/TA_PRECOS_MEDICAMENTOS.zip",
  exdir="data")
```

Descobrindo os formatos do CSV (Encoding) e ouutras coisas

```{r}
fname <-"data/TA_PRECOS_MEDICAMENTOS.csv"
locale_brasil <- locale(encoding = "ISO-8859-1",
                        decimal_mark = ",")
first3 <- read_lines(fname, n_max = 3, locale=locale_brasil)
first3[1] %>% str_count(";")
```

```{r}
guess_encoding(fname)
```
Vendo se está com todas as linhas com mesmo número de colunas


```{r}
read_lines(fname, locale=locale_brasil) %>% 
  str_count(";") %>% table
```
Atenção, o @ está explicando que as "" e a '' dentro do csv não são delimitadores de campos.

```{r}
df_medicamentos <- read_delim(fname,
                              delim=";",
                              locale=locale_brasil,
                              quote="@")
```
```{r}
read_lines(fname, locale=locale_brasil) [2084]

```

```{r}
nrow(df_medicamentos)
ncol(df_medicamentos)
```

```{r}
colnames(df_medicamentos)
```

```{r}
glimpse(df_medicamentos)
```

```{r}
df_medicamentos %>% count(NO_RAZAO_SOCIAL, sort = T)
```

